# Generated by Django 4.2.8 on 2024-01-06 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(max_length=3000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('camp', 'Campaign'), ('card', 'Card Game'), ('class', 'Classic'), ('dex', 'Dexterity'), ('draft', 'Drafting'), ('edu', 'Educational'), ('party', 'Party'), ('puz', 'Puzzle'), ('rpg', 'Role-Playing Game'), ('strat', 'Strategy'), ('war', 'Wargame'), ('oth', 'Other. Please specify')], default='camp', max_length=20)),
                ('number_of_players', models.CharField(choices=[('one_to_two', '1-2 Players'), ('one_to_four', '1-4 Players'), ('one_to_six', '1-6 Players'), ('two_to_four', '2-4 Players'), ('two_to_six', '2-6 Players'), ('two_to_eight', '2-8 Players'), ('two_to_fifteen', '2-15 Players'), ('oth', 'Other. Please specify')], default='one_to_four', max_length=20)),
                ('age_range', models.CharField(choices=[('four_plus', '4 +'), ('twelve_plus', '12 +'), ('fifteen_pus', '15 +'), ('eigtheen_plus', '18 +'), ('oth', 'Other. Please specify')], default='four_plus', max_length=20)),
                ('play_time', models.CharField(choices=[('under_one', '10-30mins'), ('hour_to_two', '1-2 hours'), ('two_to_four', '2-4 hours'), ('over_four', '4 + hours'), ('rest_of', 'The rest of your life'), ('oth', 'Other. Please specify')], default='under_one', max_length=20)),
                ('experience', models.IntegerField(choices=[(1, 'Casual'), (2, 'Medium'), (3, 'Not Suitable for Beginners'), (3, 'Hardcore'), (4, 'Friendship Ender')], default=1)),
                ('price_range', models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], default=1)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
