# Generated by Django 4.2.8 on 2024-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_options_post_number_of_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_players',
            field=models.CharField(choices=[('one_to_two', '1-2 Players'), ('one_to_four', '1-4 Players'), ('one_to_six', '1-6 Players'), ('two_to_four', '2-4 Players'), ('two_to_six', '2-6 Players'), ('two_to_eight', '2-8 Players'), ('two_to_fifteen', '2-15 Players'), ('oth', 'Other. Please specify')], default='one_to_four', max_length=100),
        ),
    ]
