# Generated by Django 4.2.8 on 2024-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_post_number_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age_range',
            field=models.CharField(choices=[('all', 'All ages'), ('four_plus', '4 +'), ('twelve_plus', '12 +'), ('fifteen_pus', '15 +'), ('eigtheen_plus', '18 +'), ('oth', 'Other')], default='four_plus', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('camp', 'Campaign'), ('card', 'Card Game'), ('class', 'Classic'), ('dex', 'Dexterity'), ('draft', 'Drafting'), ('edu', 'Educational'), ('party', 'Party'), ('puz', 'Puzzle'), ('rpg', 'Role-Playing Game'), ('strat', 'Strategy'), ('war', 'Wargame'), ('oth', 'Other')], default='camp', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_players',
            field=models.CharField(choices=[('any', 'Any'), ('one_to_two', '1-2 Players'), ('one_to_four', '1-4 Players'), ('one_to_six', '1-6 Players'), ('two_to_four', '2-4 Players'), ('two_to_six', '2-6 Players'), ('two_to_eight', '2-8 Players'), ('two_to_fifteen', '2-15 Players'), ('two_to_six', '3-6 Players'), ('two_to_eight', '3-8 Players'), ('two_to_fifteen', '3-15 Players'), ('oth', 'Other')], default='one_to_four', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='play_time',
            field=models.CharField(choices=[('under_one', '10-30mins'), ('hour_to_two', '1-2 hours'), ('two_to_four', '2-4 hours'), ('over_four', '4 + hours'), ('rest_of', 'The rest of your life'), ('oth', 'Other')], default='under_one', max_length=20),
        ),
    ]
