# Generated by Django 4.2.8 on 2024-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
