# Generated by Django 4.2.8 on 2024-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_post_image_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_players',
            field=models.CharField(choices=[('any', 'Any'), ('one_to_two', '1-2 Players'), ('one_to_four', '1-4 Players'), ('one_to_six', '1-6 Players'), ('two_to_four', '2-4 Players'), ('two_to_six', '2-6 Players'), ('two_to_eight', '2-8 Players'), ('two_to_fifteen', '2-15 Players'), ('three_to_six', '3-6 Players'), ('three_to_eight', '3-8 Players'), ('three_to_fifteen', '3-15 Players'), ('oth', 'Other')], default='one_to_four', max_length=100),
        ),
    ]
