# Generated by Django 4.2.8 on 2024-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_post_number_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age_range',
            field=models.CharField(choices=[('all', 'All ages'), ('four_plus', '4 +'), ('five_plus', '5 +'), ('six_plus', '6 +'), ('seven_plus', '7 +'), ('eight_plus', '8 +'), ('ten_plus', '10 +'), ('twelve_plus', '12 +'), ('thirteen_plus', '13 +'), ('fourteen_plus', '14 +'), ('fifteen_pus', '15 +'), ('eigtheen_plus', '18 +'), ('oth', 'Other')], default='four_plus', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_players',
            field=models.CharField(choices=[('any', 'Any'), ('one_to_two', '1-2 Players'), ('one_to_three', '1-3 Players'), ('one_to_four', '1-4 Players'), ('one_to_five', '1-5 Players'), ('one_to_six', '1-6 Players'), ('one_to_eight', '1-8 Players'), ('two_to_four', '2-4 Players'), ('two_to_five', '2-5 Players'), ('two_to_six', '2-6 Players'), ('two_to_eight', '2-8 Players'), ('two_to_fifteen', '2-15 Players'), ('three_to_four', '3-4 Players'), ('three_to_five', '3-5 Players'), ('three_to_six', '3-6 Players'), ('three_to_eight', '3-8 Players'), ('three_to_fifteen', '3-15 Players'), ('oth', 'Other')], default='one_to_four', max_length=100),
        ),
    ]
